# Generated by Django 4.2.2 on 2023-06-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieslist',
            name='img',
            field=models.ImageField(default='dddd', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
